name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]    
    steps:
    - uses: olegtarasov/get-tag@v2.1
      with:
        tagRegex: "v(.*)"
      id: tagName
    - uses: actions/checkout@v2
    - name: Use Node.js LTS 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build

    - run: npm run pack-linux
      if: runner.os == 'Linux'
    - name: Create tarball
      working-directory: dist/pkg/YellowFruit-linux-x64
      run: |
        tar -czvf YellowFruit-${{ steps.tagName.outputs.tag }}-linux-x64.tar.gz *
      if: runner.os == 'Linux'
    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with: 
        name: Linux tarball
        path: dist/pkg/YellowFruit-linux-x64/YellowFruit-${{ steps.tagName.outputs.tag }}-linux-x64.tar.gz
      if: runner.os == 'Linux'
  
    - run: npm run pack-win
      if: runner.os == 'Windows'
    - run: npm run make-winstaller
      if: runner.os == 'Windows'
    - name: Rename installer exe
      run: |
        move dist\pkg\Install-YellowFruit.exe dist\pkg\Install-YellowFruit-${{ steps.tagName.outputs.tag }}-windows.exe
      if: runner.os == 'Windows'
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with: 
        name: Windows installer
        path: dist\pkg\Install-YellowFruit-${{ steps.tagName.outputs.tag }}-windows.exe
      if: runner.os == 'Windows'

